//types.js

export const IDIOM_SET = 'IDIOM_SET';
export const SPOTIFY_SET_DATA = 'SPOTIFY_SET_DATA';
export const SPOTIFY_RESET = 'SPOTIFY_RESET';
export const MENU_RESET = 'MENU_RESET';
export const MENU_SET_SHOW_MODAL_IDIOM = 'MENU_SET_SHOW_MODAL_IDIOM';
export const MENU_SET_SHOW_MENU = 'MENU_SET_SHOW_MENU';
export const ROUTER_TURN_ON_HOME = 'ROUTER_TURN_ON_HOME';
export const ROUTER_TURN_ON_ABOUT = 'ROUTER_TURN_ON_ABOUT';
export const ROUTER_TURN_ON_SPOTIFY = 'ROUTER_TURN_ON_SPOTIFY';
export const ROUTER_TURN_OFF_HOME = 'ROUTER_TURN_OFF_HOME';
export const ROUTER_TURN_OFF = 'ROUTER_TURN_OFF';
